# Simple workflow for testing
name: Test

on:
  # Runs on pushes targeting the default branch
  push:
  # Runs on pull requests targeting the default branch
  pull_request:
    branches: ['develop']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow testing
permissions:
  contents: read

# Allow one concurrent test
concurrency:
  group: 'test'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.10.0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Test
        run: pnpm run test
